services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - 'minio-data:/data'
    command: server ~/minio --console-address :9090
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
  minio-data:
    driver: local
